<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHiucq53\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHiucq53/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHiucq53.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHiucq53\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHiucq53\appProdProjectContainer([
    'container.build_hash' => 'Hiucq53',
    'container.build_id' => '38515217',
    'container.build_time' => 1651676500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHiucq53');
